# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ouvidor CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Running Tests
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Installing dependencies
      run: yarn install
    - name: Testing
      run: yarn test
